
version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    env_file:
      - .env
    expose:
      - 8000
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - fastapi
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot
      --email seu-email@exemplo.com --agree-tos --no-eff-email
      -d seu-dominio.com && nginx -s reload"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
